// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7rWFZRySi5DSWWIRpSbpiCVuiVaS7o0',
    appId: '1:52293952399:web:ed41201a30b10dcf7621fa',
    messagingSenderId: '52293952399',
    projectId: 'final-project-iti-613b3',
    authDomain: 'final-project-iti-613b3.firebaseapp.com',
    storageBucket: 'final-project-iti-613b3.firebasestorage.app',
    measurementId: 'G-1SMHF4C26W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TnJE1xRiA9oCEDL_ZAPZsnTgFjhrgak',
    appId: '1:52293952399:android:cd3cd6da528c52727621fa',
    messagingSenderId: '52293952399',
    projectId: 'final-project-iti-613b3',
    storageBucket: 'final-project-iti-613b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3b-7J5leK3ahbEdcFoD91lePz8vpJWQM',
    appId: '1:52293952399:ios:594b59177871a83f7621fa',
    messagingSenderId: '52293952399',
    projectId: 'final-project-iti-613b3',
    storageBucket: 'final-project-iti-613b3.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectItiMalakAli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp7rWFZRySi5DSWWIRpSbpiCVuiVaS7o0',
    appId: '1:52293952399:web:4e036e8c35b200737621fa',
    messagingSenderId: '52293952399',
    projectId: 'final-project-iti-613b3',
    authDomain: 'final-project-iti-613b3.firebaseapp.com',
    storageBucket: 'final-project-iti-613b3.firebasestorage.app',
    measurementId: 'G-GBPDQTKQLF',
  );
}
